config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get 'home/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- For mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<!-- Start Header -->
	<header class="header">
		<!-- Start Navbar -->
		<nav class="navbar navbar-outro navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a href="index.html" class="navbar-brand hidden-xs">Event Lister</a>
				</div>
				<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">Sobre a Event</a></li>
						<li><a href="#">Promotores de Eventos</a></li>
						<li><a href="#">Cadastre-se</a></li>
						<li><a href="#">Login</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- End Navbar -->

		<!-- Start Img -->
		<div class="header-img">
			<%= image_tag "top-img.jpg", class: "img-responsive" %>
		</div>
		<!-- End Img -->
	</header>
	<!-- End Header -->

	<!-- ♥ ♥ ♥ -->

	<!-- Start Main -->
	<main>
		<!-- Button-Fixed -->
		<p href="#" class="help-button hidden-xs hidden-sm hide">
			<%= image_tag "help(2).png" %>
		</p>
		<!-- Button-Fixed -->
		<div class="content">
			<div class="fun">
				<div class="container">
					<div class="header-fun">
						<h1 class="text-center">Divirta-se com seus amigos</h1>
					</div>
					<div class="content-fun">
						<h3 class="text-center">Convide seus amigos para eventos e ganhe descontos nos ingressos. </h3>
					</div>
				</div>
			</div> <!-- /.fun -->

			<div class="sustainable">
				<div class="container">
					<div class="header-sustainable">
						<h1 class="text-center">Sustentabilidade é tudo</h1>
					</div>
					<div class="content-sustainable">
						<h3 class="text-center">
							Diga adeus aos ingressos de papel ou vouchers, ajude-nos a manter o meio ambiente mais sustentável.
						</h3>
					</div>
				</div>
			</div> <!-- /.sustainable -->

			<div class="ticket">
				<div class="container">
					<div class="header-ticket">
						<h1 class="text-center">Ingressos Virtuais</h1>
					</div>
					<div class="content-ticket">
						<h3 class="text-center">Com apenas um clique adquira seus ingressos de uma forma mais eficiente e segura.</h3>
					</div>
				</div>
			</div> <!-- /.ticket -->

			<div class="category">
				<!-- Header -->
				<div class="header-category">
					<div class="row">
						<div class="container">
							<div class="col-md-12">
								<h1 class="text-center">Categoria de Eventos</h1>
							</div>
						</div>
					</div>
				</div> <!-- /.header-category -->
				<!-- Content -->
				<div class="content-category text-center">
					<div class="row">
						<div class="container">
							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Festas e Baladas</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "balada.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Festivais de Comida</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "comida.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Workshops</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "cursos.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>
						</div>
					</div> <!-- /.row -->

					<div class="row">
						<div class="container">
							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Festivais de Cinema</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "teatro.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Exposições Artísticas</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "arte.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Esportes</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "esportes.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>
						</div>
					</div> <!-- /.row -->

					<div class="row">
						<div class="container">
							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Networking</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "networking.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Congressos e Seminários</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "congressos.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>

							<div class="col-md-4 cat">
								<!-- Info-Image -->
								<div class="info-category">
									<h3 class="text-center">Mostra Científica</h3>
								</div>
								<!-- Image -->
								<div class="img-category text-center">
									<%= image_tag "cientifica.jpg", class: "img-responsive img-rounded" %>
								</div>
							</div>
						</div>
					</div> <!-- /.row -->
				</div> <!-- /.content-category -->
			</div> <!-- /.category -->
		</div>
	</main>
	<!-- End Main -->

	<!-- ♥ ♥ ♥ -->

	<!-- Start Footer -->
	<footer class="footer">

		<div class="footer-right">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-github"></i></a>
		</div>

		<div class="footer-left">
			<p class="footer-links">
				<a href="#">Sobre a Event</a>
				·
				<a href="#">Promotores de Eventos</a>
				·
				<a href="#">Trabalhe conosco</a>
				·
				<a href="#">Termos de Serviços</a>
				·
				<a href="#">Política de Privacidade</a>
			</p>
		</div>

		<p>Event Lister &copy; 2017</p>
	</footer>
	<!-- End Footer -->
	<!-- The End ♥ -->
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Lister</title>
    <%= favicon_link_tag 'icon.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>